"""Node.js SDK code templates."""

from typing import Any, Dict


NODEJS_TEMPLATE = '''/**
 * {api_name} SDK - Node.js
 * Generated by Merchant Integration MCP
 */

const axios = require('axios');
const crypto = require('crypto');

/**
 * {api_description}
 * 
 * Authentication: {auth_type}
 * Base URL: {{base_url}}
 */
class {class_name} {{
    /**
     * Initialize SDK client
     * @param {{Object}} config - Configuration options
     * @param {{string}} config.apiKey - API key for authentication
     * @param {{string}} [config.apiSecret] - API secret for signature generation
     * @param {{string}} [config.baseUrl] - Base URL for API
     * @param {{number}} [config.timeout] - Request timeout in ms
     */
    constructor({{ apiKey, apiSecret = null, baseUrl = '{base_url}', timeout = 30000 }}) {{
        this.apiKey = apiKey;
        this.apiSecret = apiSecret;
        this.baseUrl = baseUrl.replace(/\\/$/, '');
        this.timeout = timeout;
        
        // Create axios instance with defaults
        this.client = axios.create({{
            baseURL: this.baseUrl,
            timeout: this.timeout,
            headers: {{
                'Content-Type': 'application/json',
                'Accept': 'application/json'
            }}
        }});
        
        // Add request interceptor for authentication
        this.client.interceptors.request.use(
            (config) => this._addAuthHeaders(config),
            (error) => Promise.reject(error)
        );
        
        // Add response interceptor for error handling
        this.client.interceptors.response.use(
            (response) => response,
            (error) => this._handleError(error)
        );
    }}
    
    /**
     * Generate HMAC-SHA256 signature
     * @private
     */
    _generateSignature(payload, timestamp) {{
        if (!this.apiSecret) {{
            throw new Error('API secret required for signature generation');
        }}
        
        const message = `${{timestamp}}.${{JSON.stringify(payload)}}`;
        return crypto
            .createHmac('sha256', this.apiSecret)
            .update(message)
            .digest('hex');
    }}
    
    /**
     * Add authentication headers to request
     * @private
     */
    _addAuthHeaders(config) {{
        const timestamp = new Date().toISOString();
        
        config.headers['X-API-Key'] = this.apiKey;
        config.headers['X-Timestamp'] = timestamp;
        
        // Add signature if secret available and payload present
        if (this.apiSecret && config.data) {{
            config.headers['X-Signature'] = this._generateSignature(
                config.data, 
                timestamp
            );
        }}
        
        return config;
    }}
    
    /**
     * Handle API errors
     * @private
     */
    _handleError(error) {{
        if (error.response) {{
            // API returned error response
            const {{ status, data }} = error.response;
            const apiError = new Error(
                data.error || `HTTP ${{status}}: Request failed`
            );
            apiError.statusCode = status;
            apiError.errorCode = data.error_code || 'UNKNOWN';
            apiError.response = data;
            throw apiError;
        }} else if (error.request) {{
            // Network error
            const networkError = new Error('Network error: No response received');
            networkError.isNetworkError = true;
            throw networkError;
        }} else {{
            // Other errors
            throw error;
        }}
    }}
    
    {methods}
}}

module.exports = {{ {class_name} }};

// Usage Example
async function main() {{
    // Initialize client
    const client = new {class_name}({{
        apiKey: process.env.API_KEY || 'your_api_key_here',
        apiSecret: process.env.API_SECRET || 'your_api_secret_here',
        baseUrl: '{base_url}'
    }});
    
    try {{
        // Make API call
        const response = await client.{example_method}({example_params});
        console.log('Success:', JSON.stringify(response.data, null, 2));
        
    }} catch (error) {{
        if (error.statusCode) {{
            console.error(`API Error ${{error.errorCode}}: ${{error.message}}`);
            console.error('Response:', error.response);
        }} else if (error.isNetworkError) {{
            console.error('Network Error:', error.message);
        }} else {{
            console.error('Error:', error.message);
        }}
    }}
}}

// Run example if called directly
if (require.main === module) {{
    main();
}}
'''


METHOD_TEMPLATE = '''
    /**
     * {method_description}
     * 
     * Endpoint: {http_method} {endpoint_path}
     *{param_docs}
     * @returns {{Promise<AxiosResponse>}} API response
     */
    async {method_name}({parameters}) {{
        const url = `{endpoint_path}`;
        
        // Build request payload
        const payload = {{{payload_dict}}};
        
        // Remove undefined/null values
        Object.keys(payload).forEach(key => {{
            if (payload[key] === undefined || payload[key] === null) {{
                delete payload[key];
            }}
        }});
        
        // Make request
        const response = await this.client.{http_method_lower}(url, payload);
        
        return response;
    }}
'''


def generate_nodejs_sdk(
    endpoint_id: str,
    endpoint_data: Dict[str, Any],
    auth_type: str = "api_key"
) -> str:
    """Generate complete Node.js SDK for an endpoint."""
    
    method_name = endpoint_id.replace('.', '_').replace('-', '_')
    http_method = endpoint_data.get('method', 'POST')
    path = endpoint_data.get('path', '/')
    
    request_fields = endpoint_data.get('request_fields', [])
    params = []
    param_docs = []
    payload_items = []
    
    for field in request_fields:
        if field.get('parent_path'):
            continue
        
        field_name = field['field_name']
        required = field.get('requirement') == 'mandatory'
        
        default = '' if required else ' = null'
        params.append(f"{field_name}{default}")
        
        param_docs.append(f"\n     * @param {{{field.get('field_type', 'any')}}} {field_name} - {field.get('description', 'No description')}")
        
        payload_items.append(f"{field_name}")
    
    method_code = METHOD_TEMPLATE.format(
        method_name=method_name,
        parameters=', '.join(params) if params else '',
        method_description=endpoint_data.get('description', f'Call {endpoint_id}'),
        http_method=http_method,
        http_method_lower=http_method.lower(),
        endpoint_path=path,
        param_docs=''.join(param_docs),
        payload_dict=', '.join(f"{item}" for item in payload_items) if payload_items else ''
    )
    
    sdk_code = NODEJS_TEMPLATE.format(
        api_name=endpoint_id.replace('.', ' ').title(),
        class_name=''.join(word.capitalize() for word in endpoint_id.replace('.', '_').split('_')),
        api_description=endpoint_data.get('description', f'{endpoint_id} API client'),
        auth_type=auth_type,
        base_url='https://api.example.com',
        methods=method_code,
        example_method=method_name,
        example_params='' if not request_fields else f"{{ {request_fields[0]['field_name']}: 'sample_value' }}"
    )
    
    return sdk_code
