"""Python SDK code templates."""

PYTHON_TEMPLATE = '''"""
{api_name} SDK - Python
Generated by Merchant Integration MCP
"""

import requests
import json
import hmac
import hashlib
import base64
from datetime import datetime
from typing import Dict, Any, Optional


class {class_name}:
    """
    {api_description}
    
    Authentication: {auth_type}
    Base URL: {base_url}
    """
    
    def __init__(
        self,
        api_key: str,
        api_secret: Optional[str] = None,
        base_url: str = "{base_url}",
        timeout: int = 30
    ):
        self.api_key = api_key
        self.api_secret = api_secret
        self.base_url = base_url.rstrip('/')
        self.timeout = timeout
        self.session = requests.Session()
        
    def _generate_signature(self, payload: str, timestamp: str) -> str:
        """Generate HMAC-SHA256 signature for request authentication."""
        if not self.api_secret:
            raise ValueError("API secret required for signature generation")
        
        message = f"{{timestamp}}.{{payload}}"
        signature = hmac.new(
            self.api_secret.encode('utf-8'),
            message.encode('utf-8'),
            hashlib.sha256
        ).hexdigest()
        return signature
    
    def _get_headers(self, payload: Optional[str] = None) -> Dict[str, str]:
        """Generate request headers with authentication."""
        timestamp = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
        
        headers = {{
            'Content-Type': 'application/json',
            'Accept': 'application/json',
            'X-API-Key': self.api_key,
            'X-Timestamp': timestamp
        }}
        
        # Add signature if payload and secret available
        if payload and self.api_secret:
            headers['X-Signature'] = self._generate_signature(payload, timestamp)
        
        return headers
    
    def _handle_response(self, response: requests.Response) -> Dict[str, Any]:
        """Handle API response with error checking."""
        try:
            data = response.json()
        except json.JSONDecodeError:
            raise APIError(
                f"Invalid JSON response: {{response.text}}",
                status_code=response.status_code
            )
        
        # Check for API-level errors
        if response.status_code >= 400:
            error_msg = data.get('error', 'Unknown error')
            error_code = data.get('error_code', 'UNKNOWN')
            raise APIError(
                f"{{error_code}}: {{error_msg}}",
                status_code=response.status_code,
                error_code=error_code,
                response=data
            )
        
        return data
    
    {methods}


class APIError(Exception):
    """Custom exception for API errors."""
    
    def __init__(
        self,
        message: str,
        status_code: Optional[int] = None,
        error_code: Optional[str] = None,
        response: Optional[Dict] = None
    ):
        super().__init__(message)
        self.status_code = status_code
        self.error_code = error_code
        self.response = response


# Usage Example
if __name__ == "__main__":
    # Initialize client
    client = {class_name}(
        api_key="your_api_key_here",
        api_secret="your_api_secret_here",
        base_url="{base_url}"
    )
    
    try:
        # Make API call
        response = client.{example_method}({example_params})
        print(f"Success: {{response}}")
        
    except APIError as e:
        print(f"API Error: {{e.error_code}} - {{e}}")
        if e.response:
            print(f"Response: {{e.response}}")
            
    except requests.RequestException as e:
        print(f"Network Error: {{e}}")
'''


METHOD_TEMPLATE = '''
    def {method_name}(
        self,{parameters}
    ) -> Dict[str, Any]:
        """
        {method_description}
        
        Endpoint: {http_method} {endpoint_path}
        
        Args:{param_docs}
        
        Returns:
            Dict containing API response
            
        Raises:
            APIError: If API returns error response
            requests.RequestException: For network errors
        """
        url = f"{{self.base_url}}{endpoint_path}"
        
        # Build request payload
        payload = {{{payload_dict}}}
        
        # Clean None values
        payload = {{k: v for k, v in payload.items() if v is not None}}
        
        # Serialize payload
        payload_json = json.dumps(payload, separators=(',', ':'))
        
        # Make request
        response = self.session.{http_method_lower}(
            url,
            headers=self._get_headers(payload_json),
            json=payload if payload else None,
            timeout=self.timeout
        )
        
        return self._handle_response(response)
'''


def generate_python_sdk(
    endpoint_id: str,
    endpoint_data: Dict[str, Any],
    auth_type: str = "api_key"
) -> str:
    """Generate complete Python SDK for an endpoint."""
    
    # Build method
    method_name = endpoint_id.replace('.', '_').replace('-', '_')
    http_method = endpoint_data.get('method', 'POST')
    path = endpoint_data.get('path', '/')
    
    # Build parameters
    request_fields = endpoint_data.get('request_fields', [])
    params = []
    param_docs = []
    payload_items = []
    
    for field in request_fields:
        if field.get('parent_path'):  # Skip nested for now
            continue
        
        field_name = field['field_name']
        field_type = field.get('field_type', 'str')
        required = field.get('requirement') == 'mandatory'
        
        # Map to Python type
        py_type = 'str'
        if field_type == 'integer':
            py_type = 'int'
        elif field_type == 'number':
            py_type = 'float'
        elif field_type == 'boolean':
            py_type = 'bool'
        elif field_type == 'object':
            py_type = 'Dict[str, Any]'
        elif field_type == 'array':
            py_type = 'List[Any]'
        
        default = '= None' if not required else ''
        params.append(f"\n        {field_name}: {py_type}{default}")
        
        param_docs.append(f"\n            {field_name}: {field.get('description', 'No description')}")
        
        payload_items.append(f'"{field_name}": {field_name}')
    
    method_code = METHOD_TEMPLATE.format(
        method_name=method_name,
        parameters=''.join(params),
        method_description=endpoint_data.get('description', f'Call {endpoint_id}'),
        http_method=http_method,
        http_method_lower=http_method.lower(),
        endpoint_path=path,
        param_docs=''.join(param_docs),
        payload_dict=', '.join(payload_items) if payload_items else ''
    )
    
    # Build full SDK
    sdk_code = PYTHON_TEMPLATE.format(
        api_name=endpoint_id.replace('.', ' ').title(),
        class_name=''.join(word.capitalize() for word in endpoint_id.replace('.', '_').split('_')),
        api_description=endpoint_data.get('description', f'{endpoint_id} API client'),
        auth_type=auth_type,
        base_url='https://api.example.com',
        methods=method_code,
        example_method=method_name,
        example_params='' if not request_fields else f"\n        {request_fields[0]['field_name']}=\"sample_value\""
    )
    
    return sdk_code
